---
title: "Figures"
author: "Anne Baranger"
date: "2024-06-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE,message=FALSE)
library(targets)
lapply(c("stringr","tidyr","dplyr","tibble", # data analysis
         "ggplot2","viridis", "ggridges","wesanderson",# plot
         "factoextra", "nlme","modi","rstan","shinystan",# stat & models
         "rworldmap" # geographic data #terre, sf
         ),require,character.only=TRUE)
theme_set(theme_minimal()) # ggplot theme
common_theme <- theme(
  # legend.position = "none",
  strip.background = element_rect(fill = "white",
                                        colour = "gray12"),
  panel.background = element_rect(fill = "white",
                                  colour = "gray12",
                                  size = 0.5, linetype = "solid"),
  plot.title = element_text(size = 12),
  axis.title = element_text(size = 10),
  axis.text = element_text(size = 10),
  strip.text = element_text(size =10),
  plot.margin = unit(c(0, 0.2, 0, 0.2), "cm")  # Example margin; adjust as needed
)

loadRData <- function(fileName){
  #loads an RData file, and returns it
  load(fileName)
  get(ls()[ls() != "fileName"])
}
```


# Introduction

```{r}
author_list<-read.csv("authors.csv")
author_first<-author_list |> 
  filter(id_authors%in%c("Michal_Bogdziewicz","James_Clark","Tong_Qiu","Georges_Kunstler","Benoit_Courbaud")) |> 
  mutate(order=case_when(id_authors=="James_Clark"~2,
                         id_authors=="Michal_Bogdziewicz"~3,
                         id_authors=="Tong_Qiu"~4,
                         id_authors=="Georges_Kunstler"~dim(author_list)[1]+1))

author_ordered<-author_list |> 
  filter(!id_authors%in%author_first$id_authors) |> 
  arrange(last) |> 
  mutate(order=row_number()+4) |> 
  rbind(author_first)

institution<-author_ordered |> 
  select(address,order) |> 
  group_by(address) |> summarise(order=min(order)) |> arrange(order) |> 
  mutate(order_instit=row_number()+1) |> select(-order)

institution |> 
  mutate(institution_name=paste0("$^{",order_instit,"}$ ",address,"\\")) |> 
  pull(institution_name) |> 
  paste(collapse = "%x%")
author_ordered |> 
  left_join(institution,by="address") |> 
  mutate(author_name=paste0(last," ",str_sub(first,1,1),".$^{",order_instit,"}$")) |> 
  arrange(order) |> 
  pull(author_name)->latex_author

paste(latex_author,collapse = ", ")
```


# Material & method

## Figure method maps

```{r}
worldmap <- sf::st_as_sf(getMap(resolution = "high"))

mastif_map<-rbind(tar_read(mastif.am,store="target_data")$df.tree, 
                  tar_read(mastif.eu,store="target_data")$df.tree) |> 
  select(plotID,lon,lat,species) |> 
  distinct() |> 
  ggplot()+
  geom_jitter(aes(lon,lat,color=species),width = 0.01,height = 0.01)+
  geom_sf(data=worldmap,fill=NA)+
  theme(legend.position = "none",
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())+
  ylim(c(25,70))+xlim(c(-145,35))
  

mastif.species.niche<-rbind(tar_read(mastif.am,store="target_data")$df.tree, 
                  tar_read(mastif.eu,store="target_data")$df.tree) |> 
  mutate(dh=pet-(map/12)) |> 
  mutate(fecEstSe=na_if(fecEstSe,0),
         fecEstMu=na_if(fecEstMu,0)) |> 
  filter(!is.na(fecEstMu)) |> filter(!is.na(fecEstSe)) |> 
  # compute numbers of observations per plot
  group_by(plotID,species,mat,dh) |> 
  summarise(n_plot=n(),
            fecEstMu_plot=mean(fecEstMu,na.rm=TRUE),
            se_plot=sqrt(sum(fecEstSe^2)/n_plot),
            cv_plot=se_plot/fecEstMu_plot) |> 
  # Compute mean of se per plot
  ungroup() |> 
  pivot_longer(cols=c("mat","dh"),
               names_to = "clim",
               values_to = "clim_val")  |> 
  filter(!is.na(clim_val)) |> 
  group_by(species,clim) |>
  summarise(#opt=weighted.quantile(clim_val,1/cv_plot,prob=0.5)[1],
    qlow=weighted.quantile(clim_val,1/cv_plot,prob=0.025)[1],#,probs=0.1)[1],
    qhigh=weighted.quantile(clim_val,1/cv_plot,prob=0.975)[1],
    qrange.mastif=qhigh-qlow,
    rhigh=weighted.quantile(clim_val,1/cv_plot, prob = 1- min(5, n())/n())[1],
    rlow=weighted.quantile(clim_val,1/cv_plot, prob = min(5, n())/n())[1],
    rrange.mastif=rhigh-rlow) |> 
  ungroup() |> 
  pivot_longer(cols=c("qlow","qhigh","rhigh","rlow"),
               names_to = "limit",
               values_to = "value_mastif") |> 
  mutate(range.mastif=case_when(grepl("q",limit)~qrange.mastif,
                                grepl("r",limit)~rrange.mastif)) |> 
  select(-qrange.mastif,-rrange.mastif)

nfi.species.niche<-rbind(tar_read(fecundity.eu_clim,store="target_nfi"),
                         tar_read(fecundity.am_clim,store="target_nfi")) |> 
  # mutate(dh=12*pet-map) |> 
  filter(BA!=0) |> 
  filter(dh>(-2500)) |>
  pivot_longer(cols=c("mat","dh"),
               names_to = "clim",
               values_to = "clim_val")  |> 
  filter(!is.na(clim_val)) |> 
  group_by(species,clim) |>
  summarise(#opt=weighted.quantile(clim_val,BA,prob=0.5)[1],
    qlow=weighted.quantile(clim_val,BA,prob=0.025)[1],#,probs=0.1)[1],
    qhigh=weighted.quantile(clim_val,BA,prob=0.975)[1],
    qrange.nfi=qhigh-qlow,
    rhigh=weighted.quantile(clim_val,BA, prob = 1- min(5, n())/n())[1],
    rlow=weighted.quantile(clim_val,BA, prob = min(5, n())/n())[1],
    rrange.nfi=rhigh-rlow) |> 
  ungroup() |> 
  pivot_longer(cols=c("qlow","qhigh","rhigh","rlow"),
               names_to = "limit",
               values_to = "value_nfi") |> 
  mutate(range.nfi=case_when(grepl("q",limit)~qrange.nfi,
                             grepl("r",limit)~rrange.nfi)) |> 
  select(-qrange.nfi,-rrange.nfi)

selection_ex<-mastif.species.niche |> 
  filter(species %in% c("fagusGrandifo","abiesProcera")) |> 
    left_join(nfi.species.niche,by=c("species","clim","limit")) |> 
  filter(grepl("q",limit)) |> 
  select(!matches("range")) |> 
  rename(Mastif=value_mastif,
         `NFI/GBIF`=value_nfi) |> 
  mutate(clim=case_when(clim=="dh"~"Moist. def.",
                        clim=="mat"~"MAT")) |> 
  pivot_longer(cols=c("Mastif","NFI/GBIF")) |> 
  pivot_wider(names_from = limit,values_from = value) |> 
  ggplot()+
  geom_linerange(aes(xmin=qlow,xmax=qhigh,color=name,y=clim),
                 size=3,
                 position = position_dodge(width=0.5,preserve="total"))+
  scale_color_manual(values=c("darkred","darkgrey"))+
  facet_wrap(clim~species,scales="free")+
  theme(strip.text=element_blank(),
        axis.text.y=element_text(angle=45),
        axis.line.x = element_line(colour="black"),
        axis.ticks.x=element_line(colour="black"))+
  labs(x="",y="",color="")
```


```{r}
nfi_map<-rbind(tar_read(fecundity.eu_clim,store="target_nfi"),
               tar_read(fecundity.am_clim,store="target_nfi")) |> 
  select(plot,lon,lat,species) |> 
  distinct() |> 
  ggplot()+
  geom_hex(aes(lon,lat),bins=100)+
  geom_sf(data=worldmap,fill=NA)+
  theme(legend.position = c(0.5,0.1),
        legend.direction = "horizontal",
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())+
  scale_fill_gradient(low="lightblue",high="darkblue",breaks=c(0,500,1500,3000))+
  ylim(c(25,70))+xlim(c(-145,35))

fec_map<-tar_read(fecundity.fit.25,store="target_fit_margin") |> 
  filter(species=="fagusGrandifo") |> 
  select(plot,lon,lat,species,fecGmMu) |> 
  distinct() |> 
  ggplot()+
  geom_point(aes(lon,lat,color=fecGmMu))+
  geom_sf(data=worldmap,fill=NA)+
  theme(legend.position=c(0.8,0.3),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())+
  scale_color_gradientn(colours=viridis(n=15),trans="log",breaks=c(0,5,100,1000,10000))+
  ylim(c(25,50))+xlim(c(-100,-60))+
  labs(color="Fecundity (g)")

margin_map<-tar_read(fecundity.fit.25,store="target_fit_margin") |> 
  filter(species=="fagusGrandifo") |> 
  select(plot,lon,lat,species,margin.temp) |> 
  mutate(margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold",
                               TRUE~"Other")) |> 
  distinct() |> 
  ggplot()+
  geom_point(aes(lon,lat,color=margin.temp))+
  geom_sf(data=worldmap,fill=NA)+
  theme(legend.position=c(0.8,0.3),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank())+
  scale_color_manual(values=c("blue","red","grey"))+
  ylim(c(25,50))+xlim(c(-100,-60))+
  labs(color="Margin type")


```



```{r}
tar_load(c(phylo.select),store="target_nfi")
data_gbif=tar_read(data_gbif_filtered,store="target_gbif")

mastif_data<-rbind(tar_read(mastif.am,store="target_data_2")$df.tree, 
                  tar_read(mastif.eu,store="target_data_2")$df.tree) |> 
  mutate(dh=pet-(map/12)) |> 
  mutate(fecEstSe=na_if(fecEstSe,0),
         fecEstMu=na_if(fecEstMu,0)) |> 
  filter(!is.na(fecEstMu)) |> filter(!is.na(fecEstSe)) |> 
  # compute numbers of observations per plot
  group_by(plotID,lon,lat,species,mat,dh) |> 
  summarise(n_plot=n(),
            fecEstMu_plot=mean(fecEstMu,na.rm=TRUE),
            se_plot=sqrt(sum(fecEstSe^2)/n_plot),
            cv_plot=se_plot/fecEstMu_plot) |> 
  # Compute mean of se per plot
  ungroup() 
  
nfi_data<-rbind(tar_read(fecundity.eu_clim,store="target_nfi_2"),
                tar_read(fecundity.am_clim,store="target_nfi_2")) |> 
  # mutate(dh=12*pet-map) |> 
  filter(BA!=0) |> 
  filter(dh>(-2500)) |>
  group_by(plot,lon,lat,species,mat,dh) |> 
  summarise(n=n())
sf::sf_use_s2(FALSE)
usmap <- sf::st_as_sf(getMap(resolution = "high")) |> 
  sf::st_crop(xmin=-135,xmax=-55,ymin=18,ymax=65)
eumap <- sf::st_as_sf(getMap(resolution = "high")) |> 
  sf::st_crop(xmin=-10,xmax=35,ymin=35,ymax=70)

sp="acerRubrum"
littlemap<-read.csv("data/USTreeAtlas-main/Little_datatable.csv")
  
sp_l<-phylo.select[phylo.select$species==sp,"species_l"]
s_p<-str_replace(sp_l," ","_")
splittle<-littlemap |> filter(Latin.Name==sp_l) |> pull(SHP..)
if(phylo.select[phylo.select$species==sp,"block"]=="america"){
  continent.map=usmap
  species_map=sf::read_sf(dsn=paste0("data/USTreeAtlas-main/shp/",splittle,"/"),
                          layer=splittle) |> 
    sf::st_set_crs(sf::st_crs(eumap))
  }
if(phylo.select[phylo.select$species==sp,"block"]=="europe"){
  continent.map=eumap
  if(file.exists(paste0("data/chorological_maps_dataset/",sp_l,"/shapefiles/",s_p,"_syn_plg.dbf"))){
    file.sp=paste0(s_p,"_syn_plg")
    }else{
      file.sp=paste0(s_p,"_plg")
      }
  species_map=sf::read_sf(dsn=paste0("data/chorological_maps_dataset/",sp_l,"/shapefiles/"),
                          layer=file.sp) |>
    sf::st_set_crs(sf::st_crs(eumap))
  }
contbox=sf::st_bbox(continent.map)
mastif.sp<-mastif_data[mastif_data$species==sp,]
gbif.sp<-data_gbif[data_gbif$species==sp_l,] |> 
  filter(decimallongitude<contbox[["xmax"]],
         decimallongitude>contbox[["xmin"]],
         decimallatitude<contbox[["ymax"]],
         decimallatitude>contbox[["ymin"]])
nfi.sp<-nfi_data[nfi_data$species==sp,] |> 
  mutate(margin=case_when(mat<=quantile(mat, probs=0.25)[[1]]~"cold",
                          mat<quantile(mat, probs=0.5+0.25/2)[[1]]&
                            mat>quantile(mat, probs=0.5-0.25/2)[[1]]~"midtemp",
                          mat>=quantile(mat, probs=0.75)[[1]]~"hot"))
ggplot()+
  geom_sf(data=continent.map,fill="tan",alpha=0.4,color=NA)+
  geom_point(data=gbif.sp,aes(x=decimallongitude,y=decimallatitude),alpha=0.2,color="darkgrey",size=0.2)+
  geom_point(data=mastif.sp,aes(x=lon,y=lat),color="red",size=0.4)+
  geom_sf(data=species_map,fill=NA,color="blue")+
  theme(axis.title = element_blank(),
        axis.text = element_blank())->plot.gbif
ggplot()+
  geom_sf(data=continent.map,fill="tan",alpha=0.4,color=NA)+
  geom_point(data=nfi.sp,aes(x=lon,y=lat),alpha=0.2,color="darkgrey",size=0.2)+
  geom_point(data=mastif.sp,aes(x=lon,y=lat),color="red",size=0.4)+
  geom_sf(data=species_map,fill=NA,color="blue")+
  theme(axis.title = element_blank(),
        axis.text = element_blank())->plot.nfi

gbif.sp |> dplyr::select(species,mat,dh)  |> 
  pivot_longer(cols=c("mat","dh"),names_to="clim",values_to = "quantile") |>
  group_by(clim) |> summarise(q05_gbif=quantile(quantile,probs=0.05,na.rm=TRUE),
                              q95_gbif=quantile(quantile,probs=0.95,na.rm=TRUE)) -> quant.gbif
nfi.sp |> select(species,mat,dh)  |> 
  pivot_longer(cols=c("mat","dh"),names_to="clim",values_to = "quantile") |>
  group_by(clim) |> summarise(q05_nfi=quantile(quantile,probs=0.05,na.rm=TRUE),
                              q95_nfi=quantile(quantile,probs=0.95,na.rm=TRUE)) -> quant.nfi


mastif.sp |> select(species,mat,dh) |> 
  pivot_longer(cols=c("mat","dh"),names_to="clim",values_to = "clim_val") |> 
  # left_join(quant.gbif) |>
  left_join(quant.nfi) |> 
  ggplot(aes(clim_val))+
  geom_histogram(alpha=0.5)+
  # geom_vline(aes(xintercept=q05_gbif,color="gbif"))+
  # geom_vline(aes(xintercept=q95_gbif,color="gbif"))+
  geom_vline(aes(xintercept=q05_nfi,color="nfi"))+
  geom_vline(aes(xintercept=q95_nfi,color="nfi"))+
  facet_wrap(~clim,scales = "free")+
  theme(axis.title = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "bottom")+
  labs(color="Quantiles from:")-> plot.var
ggplot()+
  geom_hex(data=gbif.sp,aes(x=mat,y=dh))+
  scale_fill_continuous(type = "viridis") +
  geom_point(data=mastif.sp,aes(x=mat,y=dh),color="red")

plot2<-cowplot::plot_grid(plot.gbif,plot.nfi, ncol = 2, labels = c("GBIF x MASTIF", "NFI x MASTIF"))
plot3 <-cowplot::plot_grid(plot2,plot.var, nrow = 2,rel_heights =  c(1,0.5))
# ggsave(filename = paste0("species_map/",sp,".png"),width=8,height = 8.5, plot = plot3)



```


## Figure focus on one species

```{r}
ecoregions=sf::read_sf(dsn="data/WWF/official", #read ecoregions
                         layer="wwf_terr_ecos") |>
    select(BIOME,ECO_NAME,geometry) |> 
    filter(!BIOME%in%c(98,99)) |> 
    mutate(ECO_NUM=as.numeric(as.factor(ECO_NAME)))
tar_load(mastif.am,store="target_data")
tar_load(stemData_am,store="target_nfi")

stemAcerRubrum<-stemData_am$plot_shade |> 
  filter(species=="fagusGrandifo") |> 
  select(plot,lat,lon,mean_dbh,shade_min,dh,mat,cec30,slope,aspect,ISP,SIZE) |> 
  rename(Temperature=mat,
         `Moisture deficit`=dh,
         `Mean diameter`=mean_dbh,
         `Min shade index`=shade_min,
         CEC=cec30,
         Aspect=aspect,
         Slope=slope) |> 
  drop_na()

pca=prcomp(stemAcerRubrum[,c("Temperature","Moisture deficit","CEC","Slope","Aspect")],scale=TRUE)
pca_biot=prcomp(stemAcerRubrum[,c("Mean diameter","Min shade index")],scale=TRUE)

fviz_pca_var(pca,
           axes=c(1,2),
           geom.var=c("arrow","text"),
           col.var="black",
           col.ind=NA,
           alpha.ind=0.05,
           col.circle = NA
           ) +
  common_theme+
  theme(panel.grid = element_blank(),
        plot.title = element_text(hjust = -0.25,size=10))+
  ylim(c(-0.15,1.1))+
  labs(title = "A. PCA of MASTIF abiotic covariates")+
  coord_fixed(ratio=1) ->a

cbind(stemAcerRubrum,
      predict(pca,stemAcerRubrum)) |>
  filter(PC1>quantile(PC1,probs=0.05),
         PC1<quantile(PC1,probs=0.95)) |> 
  rename(`B. PCA axis 1`=PC1) |> 
  ggplot() +
  geom_sf(data=ecoregions,fill="#e9ecef")+
  geom_point(aes(x = lon, y = lat, color = `B. PCA axis 1`),
             size=0.2,
             alpha = 0.4) +
  scale_color_gradientn(colours = wes_palette(type="continuous",name="Zissou1")) +
  ylim(c(25, 50)) + xlim(c(-100, -65))+
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        plot.title = element_text(hjust = 0,size=10),
        panel.grid=element_blank(),
        legend.position=c(0.85,0.3))+
  # common_theme+
  labs(color="",title="B. PC1 of abiotic variables PCA")->b


cowplot::plot_grid(a,b,nrow=2,rel_widths = c(0.92,1))-> p1


fviz_pca_var(pca_biot,
           axes=c(1,2),
           geom.var=c("arrow","text"),
           col.var="black",
           col.ind=NA,
           alpha.ind=0.05,
           col.circle = NA
           ) +
  common_theme+
  theme(panel.grid = element_blank(),
        plot.title = element_text(hjust = -0.25,size=10))+
  ylim(c(-0.2,1.1))+
  labs(title = "A. PCA of MASTIF abiotic covariates")+
  coord_fixed(ratio=1) ->c

cbind(stemAcerRubrum,
      predict(pca_biot,stemAcerRubrum)) |>
  filter(PC1>quantile(PC1,probs=0.05),
         PC1<quantile(PC1,probs=0.95)) |> 
  rename(`B. PCA axis 1`=PC1) |> 
  ggplot() +
  geom_sf(data=ecoregions,fill="#e9ecef")+
  geom_point(aes(x = lon, y = lat, color = `B. PCA axis 1`),
             size=0.2,
             alpha = 0.4) +
  scale_color_gradientn(colours = wes_palette(type="continuous",name="Zissou1")) +
  ylim(c(25, 50)) + xlim(c(-100, -65))+
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        plot.title = element_text(hjust = 0,size=10),
        panel.grid=element_blank(),
        legend.position=c(0.85,0.3))+
  # common_theme+
  labs(color="",title="B. PC1 of biotic variables PCA")->d


cowplot::plot_grid(c,d,nrow=2,rel_widths = c(0.92,1))-> p2

mastif.point=mastif.am$df.alltree |>
  filter(species=="acerRubrum") |> 
  select(plotID,species,lon,lat) |> 
  unique()

fec_map<-stemAcerRubrum |> 
  mutate(lISP = scale(log(ISP / mean(ISP)))) %>%
    filter(lISP>quantile(lISP,probs=0.05),
           lISP<quantile(lISP,probs=0.95)) |> 
  rename(`B. Mean Fecundity`=lISP) |> 
  ggplot() +
  geom_sf(data=ecoregions,fill="#e9ecef")+
  geom_point(aes(x = lon, y = lat, color = `B. Mean Fecundity`),
             size=0.2,
             alpha = 0.4) +
  geom_point(data=mastif.point,
             aes(x=lon,y=lat),
             size=0.8,
             alpha=1,
             color="grey10") +
  scale_color_gradientn(colours = wes_palette(type="continuous",name="Zissou1")) +
  ylim(c(25, 50)) + xlim(c(-100, -65))+
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        plot.title = element_text(hjust = 0,size=10),
        panel.grid=element_blank(),
        legend.position="none")+
  # common_theme+
  labs(color="",title="B. Mean Fecundity")->b

plot_grid(a,b,c,d,
          scales=c(1,0.9,0.9,0.9),
          # labels_x=c(10,40,0),
          # labels_y=-10,
          ncol=2,
          label_fontfamily="plain")->plot
plot
```

# Results

```{r data, include=FALSE}

# load necessary data #
tar_load(species_selection_large,store="target_nfi")

## species selection ##
tar_load(sp.select.eu,store="target_nfi")
tar_load(sp.select.am,store="target_nfi")
tar_load(species_class,store="target_nfi")
tar_load(species.biome,store="target_fit")


worldmap <- sf::st_as_sf(getMap(resolution = "high"))

```

## 1

### data
```{r}
fitspecies<-tar_read(fitspecies_25,store="target_fit_margin")
fecundity.fit<-tar_read(fecundity.fit.25,store="target_fit_margin")
fitcontinentdiscrete<-tar_read(fitcontinentdiscrete_25,store="target_fit_margin")
```


### figure
```{r}
species_n=fecundity.fit |> 
  filter(margin.temp%in%c("hot","cold")) |> 
  select(zone,margin.temp,species) |> 
  unique() |> 
  group_by(zone,margin.temp) |> 
  summarise(n=paste0("(",n(),")"))

signif<- fitcontinentdiscrete |>
  ungroup() |> 
  group_by(zone,margin.temp) |> 
  summarise(mean=mean(posterior),
            q05=quantile(posterior,prob=0.05),
            q95=quantile(posterior,prob=0.95)) |> 
  mutate(signif=(sign(q05)==sign(q95)))

text=fitcontinentdiscrete |> 
  filter(margin.temp%in%c("cold","hot"))|> 
  group_by(zone,margin.temp) |> summarise(med=median(posterior),ext=min(posterior)-0.1) |> 
  left_join(species_n,by=c("zone","margin.temp")) |>
  left_join(signif) |>
  mutate(star=if_else(signif,"*",""),
         margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold"),
         zone=factor(zone,level=c("west","east","europe")))

data_env<-fecundity.fit |> 
  filter(margin.temp%in%c("cold","hot"))|> 
  group_by(zone,species,margin.temp) |> 
  summarise(med.dh=median(dh),
            med.mat=median(mat)) |> 
  group_by(margin.temp,zone) |> 
  mutate(max.mat=max(med.mat),
         min.mat=min(med.mat)) 
fitcontinentdiscrete |> 
  filter(margin.temp%in%c("cold","hot"))|> 
  mutate(margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold")) |>
  ggplot()+
  geom_density_ridges(aes(x=posterior,y=zone,fill=zone),
                      scale=0.6,color=NA)+
  geom_vline(xintercept = 0)+
  geom_text(data=text,aes(label=star,x=med,y=zone,color=zone),vjust=1.2,size=6)+
  geom_text(data=text,aes(label=n,x=med,y=zone),vjust=-0.5,size=3)+
  scale_fill_manual(values=c("firebrick4","firebrick1","slateblue"))+
  scale_color_manual(values=c("firebrick4","firebrick1","slateblue"),guide="none")+
  facet_wrap(~margin.temp,nrow=2)+
  common_theme+
  theme(axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        legend.position = c(0.13,0.13),
        legend.background = element_rect(fill = "white",
                                         size = 0.5),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())+
  labs(x="Relative log-fecundity (species as random effect)",
       title="A. Posterior of continent scale model",
       fill="Zone") ->boxp
  
```

```{r}
model_data <-fitspecies |>
  ungroup() |> 
  left_join(data_env,by=c("species","margin.temp")) |> 
  filter(margin.temp%in%c("cold","hot"))|> 
  mutate(margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold")) |> 
  group_by(zone,species,margin.temp,med.mat,max.mat,min.mat) |> 
  summarise(med.ISP=median(posterior),
            q05=quantile(posterior, prob=0.05)[[1]],
            q95=quantile(posterior, prob=0.95)[[1]]) |>
  mutate(signif=!(q05<0&q95>0)) |> ungroup() |> 
  # filter(signif) |> 
  group_by(margin.temp,zone) |> 
  do({
    model = lm(med.ISP ~ med.mat, data = .)
    anova_result <- anova(model)
    p_value <- anova_result$`Pr(>F)`[1]
    data.frame(broom::tidy(model), p_value = p_value, .[1, ])
  }) %>% 
  filter(p_value<0.1) |>
  # filter(zone=="europe") |> 
  dplyr::select(term,estimate,zone,margin.temp,max.mat,min.mat)
model_data=model_data |> 
  pivot_wider(names_from = term,
              values_from = estimate) |> 
  crossing(mat.pred=seq(-10,25,0.1)) |> 
  filter((mat.pred>min.mat)&(mat.pred<max.mat)) |> 
  mutate(pred.isp=`(Intercept)`+mat.pred*med.mat) 

fitspecies |>
  left_join(data_env) |> 
  filter(margin.temp%in%c("cold","hot"))|> # &margin.deficit=="arid" 
  mutate(margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold")) |> 
  group_by(zone,species,margin.temp,med.mat) |> 
  summarise(med.ISP=median(posterior),
            q05=quantile(posterior, prob=0.05)[[1]],
            q95=quantile(posterior, prob=0.95)[[1]]) |> 
  mutate(signif=!(q05<0&q95>0)) |> 
  ungroup() |> 
  ggplot()+
  geom_point(aes(med.mat,med.ISP,color=zone,shape=signif))+
  geom_linerange(aes(x=med.mat,ymin=q05,ymax=q95,color=zone))+
  geom_line(data = model_data,
            aes(mat.pred,pred.isp,color=zone),
            linewidth=1) +
  geom_hline(yintercept = 0,color="gray32")+
  geom_vline(xintercept = 0,color="gray32")+
  common_theme+
  theme(legend.position = "none")+
  scale_color_manual(values=c("firebrick1","slateblue","firebrick4"))+
  scale_shape_manual(values=c(1,19))+
  # scale_y_continuous(breaks = c(-2,-1,-0.5,0.5,1,2))+
  labs(title="B. Posterior at the species scale",
       y="Relative log-fecundity (by species)",
       x="Mean annual temperature of the margin")+
  facet_wrap(~margin.temp,nrow = 2)->plt


cowplot::plot_grid(boxp,plt,ncol=2,rel_widths = c(2,1.5))  -> p
p
# ggsave( p,
#         filename = "figure/main_fig_1_margin.png",
#         scale=1.2,
#         dpi = 600,
#         width = 17,
#         height=12,
#         units = "cm")


```



```{r}
tar_read(fitspecies_25,store="target_fit_2") |>
  ungroup() |> 
  group_by(zone,species) |> 
  mutate(margin.deficit=case_when(dh<weighted.quantile(dh,w=BA, prob=0.05)[[1]]~"humid",
                              dh<weighted.quantile(dh,w=BA, prob=0.525)[[1]]&
                                 dh>weighted.quantile(dh,w=BA, prob=0.475)[[1]]~"midhum",
                               dh>weighted.quantile(dh,w=BA, prob=0.95)[[1]]~"arid")) |> 
  filter(margin.temp%in%c("cold","hot"))|> # &margin.deficit=="arid" 
  mutate(margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold")) |> 
  group_by(zone,species,margin.temp) |> 
  summarise(med.ISP=weighted.quantile(fit,w=1/(quant95-quant05), prob=0.5)[[1]],
            q05=weighted.quantile(fit,w=1/(quant95-quant05), prob=0.05)[[1]],
            q95=weighted.quantile(fit,w=1/(quant95-quant05), prob=0.95)[[1]],
            mean.ISP=mean(fit),
            med.dh=median(dh),
            med.mat=median(mat)) |>
  mutate(signif=!(q05<0&q95>0)) |> select(zone,species,margin.temp,med.ISP,q05,q95) |> 
  group_by(zone,margin.temp) |> 
  summarise(m=weighted.quantile(med.ISP,w=1/(q95-q05), prob=0.5)[[1]])
```

### results

```{r}
fitcontinentdiscrete |>
  ungroup() |> 
  group_by(margin.temp) |> 
  summarise(mean=mean(posterior),
            q05=quantile(posterior,prob=0.05),
            q95=quantile(posterior,prob=0.95)) |> 
  mutate(signif=(sign(q05)==sign(q95))) |> 
  mutate(ltx=paste0(round(mean,digits = 2)," [",round(q05,digits=2),",",round(q95,digits = 2),"]"))
signif |> 
  mutate(ltx=paste0(round(mean,digits = 2)," [",round(q05,digits=2),",",round(q95,digits = 2),"]"))
```


```{r}
fitspecies |>
  left_join(data_env) |> 
  filter(margin.temp%in%c("cold","hot"))|> # &margin.deficit=="arid" 
  mutate(margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold")) |> 
  group_by(zone,species,margin.temp,med.mat) |> 
  summarise(med.ISP=median(posterior),
            q05=quantile(posterior, prob=0.05)[[1]],
            q95=quantile(posterior, prob=0.95)[[1]]) |> 
  mutate(signif=!(q05<0&q95>0)) |> 
  ungroup() |> 
  mutate(pos_eff=med.ISP>0) |> group_by(margin.temp) |> mutate(n_sp=n()) |> ungroup() |> 
  group_by(n_sp,margin.temp,pos_eff) |> 
  summarise(prop_signif=sum(signif)/n_sp,
            n_signif=sum(signif)) |> 
  distinct()

fitspecies |>
  left_join(data_env) |> 
  filter(margin.temp%in%c("cold","hot"))|> # &margin.deficit=="arid" 
  mutate(margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold")) |> 
  group_by(zone,species,margin.temp,med.mat) |> 
  summarise(med.ISP=median(posterior),
            q05=quantile(posterior, prob=0.05)[[1]],
            q95=quantile(posterior, prob=0.95)[[1]]) |> 
  filter((sign(q05)==sign(q95))) |> ungroup() |> 
  group_by(margin.temp) |> summarise(med_eff=mean(med.ISP))
  


model_data <- fitspecies |>
  ungroup() |> 
  left_join(data_env,by=c("species","margin.temp")) |> 
  filter(margin.temp%in%c("cold","hot"))|> 
  mutate(margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold")) |> 
  group_by(zone,species,margin.temp,med.mat,max.mat,min.mat) |> 
  summarise(med.ISP=median(posterior),
            q05=quantile(posterior, prob=0.05)[[1]],
            q95=quantile(posterior, prob=0.95)[[1]]) |>
  mutate(signif=!(q05<0&q95>0)) |> ungroup() |> 
  # filter(signif) |> 
  group_by(margin.temp,zone) |> 
  do({
    model = lm(med.ISP ~ med.mat, data = .)
    data.frame(broom::tidy(model), .[1, ])
  }) 
model_data
```

### Theoritical model

```{r}
library(dplyr)
library(ggplot2)
library(lme4)

# Set parameters
temp_min <- 5
temp_max <- 23
nsp1 <- 1000

# Generate data for four species
generate_species_data <- function(n, temp_min, temp_max, mean_func, sd1, sd2, sp_name) {
  temp <- runif(n, temp_min, temp_max)
  isp <- rnorm(n, mean = mean_func(temp), sd = sd1) + rnorm(n, 0, sd2)
  data.frame(temp, isp, sp = sp_name)
}

sp1 <- generate_species_data(nsp1, temp_min, temp_max, function(temp) 100 - 1.5 * temp, 3, 5, "sp1")
sp2 <- generate_species_data(1000, temp_min, temp_max, function(temp) 10 + 0.5 * temp, 1, 0, "sp2")
sp3 <- generate_species_data(1000, temp_min, temp_max, function(temp) 30 + 0.1 * temp, 1, 0, "sp3")
sp4 <- generate_species_data(1000, temp_min, temp_max, function(temp) 80 + 1.5 * temp, 1, 0, "sp4")

# Combine all species data
mod <- bind_rows(sp1, sp2, sp3, sp4) %>%
  group_by(sp) %>%
  mutate(margin.temp = case_when(
    temp <= quantile(temp, probs = 0.25) ~ "cold",
    temp < quantile(temp, probs = 0.625) & temp > quantile(temp, probs = 0.375) ~ "midtemp",
    temp >= quantile(temp, probs = 0.75) ~ "hot"
  ),
  margin.temp = factor(margin.temp, levels = c("midtemp", "cold", "hot")),
  lisp = log(isp / mean(isp))) %>%
  filter(margin.temp%in%c("hot","cold"))

# Plot the data
mod %>%
  ggplot(aes(margin.temp, lisp)) +
  geom_boxplot() +
  facet_wrap(~ sp)

# Fit the linear mixed-effects model
lme_mod <- lmer(lisp ~ margin.temp + (1 | sp), data = mod)
lme_mod_rand <- lmer(lisp ~ margin.temp + (margin.temp | sp), data = mod)
summary(lme_mod)
summary(lme_mod_rand)
```


## 2

### Data
```{r}
fitbiomediscrete<-tar_read(fitbiomediscrete_25,store="target_fit_margin")
fecundity.fit<-tar_read(fecundity.fit.25,store="target_fit_margin")
tar_load(species.biome,store="target_fit_margin")
```


### Figure

```{r}
species_n=fecundity.fit |> 
  select(-biome) |> 
  left_join(species.biome) |> 
  filter(margin.temp%in%c("hot","cold")) |> 
  select(biome,margin.temp,species) |> 
  unique() |> 
  group_by(biome,margin.temp) |> 
  summarise(n=paste0("(",n(),")"))

signif<- fitbiomediscrete |>
  ungroup() |> 
  group_by(biome,margin.temp) |> 
  filter(margin.temp %in%  c("cold","hot")) |> 
  summarise(mean=mean(posterior),
            q05=quantile(posterior,prob=0.05),
            q95=quantile(posterior,prob=0.95))|> 
  mutate(signif=(sign(q05)==sign(q95)))

text=fitbiomediscrete |> 
  filter(margin.temp%in%c("cold","hot"))|> 
  group_by(biome,margin.temp) |> summarise(med=median(posterior),ext=min(posterior)-0.1) |> 
  left_join(species_n,by=c("biome","margin.temp")) |>
  left_join(signif) |>
  mutate(star=if_else(signif,"*",""),
         margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold"),
         biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Dry",
                         biome==13~"Desert"))
fitbiomediscrete |> 
  mutate(margin.temp=ifelse(margin.temp=="hot","Hot",
                            ifelse(margin.temp=="cold","Cold","midtemp")),
         margin.temp=factor(margin.temp,levels=c("Cold","midtemp","Hot")),
         biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Dry",
                         biome==13~"Desert")) |> 
  filter(margin.temp!="midtemp") |>
  ggplot()+
  geom_density_ridges(aes(x=posterior,y=biome,fill=biome),
                      scale=1.1,color=NA)+
  geom_text(data=text,aes(label=star,x=med,y=biome,color=biome),vjust=1.2,size=6)+
  geom_text(data=text,aes(label=n,x=med,y=biome),vjust=-0.5,size=3)+
  geom_vline(xintercept = 0)+
  scale_fill_manual(values=c("turquoise3","tomato2","seagreen4","springgreen2"))+
  scale_color_manual(values=c("turquoise3","tomato2","seagreen4","springgreen2"),guide="none")+
  facet_wrap(~margin.temp,ncol=2)+
  common_theme+
  theme(#axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        legend.position = "none",
        # legend.background = element_rect(fill = "white",
        #                                  size = 1),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())+
  labs(x="Posterior of the relative log-fecundity",
       fill="Biome")->p2
p2
# ggsave( p2,
#         filename = "figure/main_fig_2_margin_2.png",
#         scale=1.1,
#         dpi = 600,
#         width = 15,
#         height=8,
#         units = "cm")
```

### Results
```{r}
signif |> 
  mutate(ltx=paste0(round(mean,digits = 2)," [",round(q05,digits=2),",",round(q95,digits = 2),"]"))
fecundity.fit |> filter(species%in% species_selection_large) |> select(biome,species) |> unique() |> group_by(biome) |> summarise(n=n()) 
```


## 3

### data
```{r}
fitbiomecontinuous<-tar_read(fitbiomecontinuous_25,store="target_fit_margin")
fecundity.fit<-tar_read(fecundity.fit.25,store="target_fit_margin")
species.biome<-tar_read(species.biome,store="target_fit_margin")
fitbiomediscrete<-tar_read(fitbiomediscrete_25,store="target_fit_margin")
```

### Figure

```{r}
species_n=fecundity.fit |> 
  select(-biome) |> 
  left_join(species.biome) |> 
  filter(margin.temp%in%c("hot","cold")) |> 
  filter(dh_valid) |> 
  select(biome,margin.temp,species) |> 
  unique() |> 
  group_by(biome,margin.temp) |> 
  summarise(n=paste0("(",n(),")"))

signif<- fitbiomediscrete |>
  ungroup() |> 
  group_by(biome,margin.temp) |> 
  filter(margin.temp %in%  c("cold","hot")) |> 
  summarise(mean=mean(posterior),
            q05=quantile(posterior,prob=0.05),
            q95=quantile(posterior,prob=0.95))|> 
  mutate(signif=(sign(q05)==sign(q95)))

text=fitbiomediscrete |> 
  filter(margin.temp%in%c("cold","hot"))|> 
  group_by(biome,margin.temp) |> summarise(med=median(posterior),ext=min(posterior)-0.1) |> 
  left_join(species_n,by=c("biome","margin.temp")) |>
  left_join(signif) |>
  mutate(star=if_else(signif,"*",""),
         margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold"),
         biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Dry",
                         biome==13~"Desert"))

fitbiomecontinuous |> 
  mutate(biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Mediterranean",
                         biome==13~"Desert")) |> 
  filter(margin.temp%in%c("hot")) |> 
  filter(dh>(-4000)) |> 
  filter(abs(log(dISP)-mean)<7.5) |> 
  mutate(dh.cat=as.numeric(as.character(cut(dh,
                    breaks = c(-Inf,-300,-275,-250,-225,-200,-175,-150,-125,-100,-75,-50,-25,0,25,50,75,100,125,150,175,200,225,250,275,300,Inf),
                    labels = c(-337.5,-287.5,-262.5,-237.5,-212.5,-187.5,-162.5,-137.5,-112.5,-87.5,-62.5,-37.5,-12.5,12.5,37.5,62.5,87.5,112.5,137.5,162.5,187.5,212.5,237.5,262.5,287.5,312.5))))) |> 
  ggplot()+
  # geom_point(aes(dh,log(dISP)-mean,color=margin.temp),size=0.6,alpha=0.05)+
  geom_ribbon(aes(x=dh,ymin=quant05,ymax=quant95,fill=biome),alpha=0.8)+
  geom_line(aes(dh,fit),size=0.2,color="black")+
  geom_boxplot(aes(as.numeric(dh.cat),log(dISP)-mean,group=dh.cat,fill=biome),linewidth=0.3,outlier.colour = NA)+
  # geom_boxplot(aes(dh,y=-12,color=margin.temp),position=position_dodge(width=2),
  #              outlier.colour = NA)+
  scale_fill_manual(values=c("turquoise3","tomato2","seagreen4","springgreen3"))+
  common_theme+
  theme(legend.position = "none")+
  labs(fill="Biome",
       y="Log ratio of fecundity \n relative to the species mean",
       x="Moisture deficit (mm)")+
  facet_wrap(~biome,nrow = 4)-> p3
p3
fitbiomecontinuous |> 
  mutate(biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Mediterranean",
                         biome==13~"Desert")) |> 
  filter(margin.temp=="hot",biome=="Mediterranean") |> 
  filter(dh>(-4000)) |> 
  filter(abs(log(dISP)-mean)<7.5) |> 
  mutate(dh.cat=as.numeric(as.character(cut(dh,
                    breaks = c(-Inf,-300,-275,-250,-225,-200,-175,-150,-125,-100,-75,-50,-25,0,25,50,75,100,125,150,175,200,225,250,275,300,Inf),
                    labels = c(-337.5,-287.5,-262.5,-237.5,-212.5,-187.5,-162.5,-137.5,-112.5,-87.5,-62.5,-37.5,-12.5,12.5,37.5,62.5,87.5,112.5,137.5,162.5,187.5,212.5,237.5,262.5,287.5,312.5))))) |> 
  pivot_longer(cols=c("fit","quant05","quant95")) |> 
  ggplot()+
  geom_boxplot(aes(as.factor(dh.cat),value))

# ggsave( p3,
#         filename = "figure/main_fig_3.png",
#         scale=1.1,
#         dpi = 600,
#         width = 8,
#         height=15,
#         units = "cm")
```
### results

```{r}
slope_biome=data.frame(biome=c(4,5,6,12),slope_med=NA,slope_q05=NA,slope_q95=NA)
for (b in 1:dim(slope_biome)[1]){
  fit<-loadRData(paste0("model/biome_continous_25_margin/anova_",slope_biome$biome[b],".RData"))
  post_slope=as.data.frame(fit) |> select(c("beta[1]","beta[4]")) |>
  mutate(slope=`beta[1]`+`beta[4]`) |> summarise(mean=mean(slope),q05=quantile(slope,probs = 0.05),q95=quantile(slope,probs = 0.95))
  slope_biome$slope_med[b]=post_slope$mean
  slope_biome$slope_q05[b]=post_slope$q05
  slope_biome$slope_q95[b]=post_slope$q95
  
}

slope_biome$signif=(sign(slope_biome$slope_q05)==sign(slope_biome$slope_q95))
slope_biome<-slope_biome |> 
  mutate(biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Dry",
                         biome==13~"Desert"),
         slope=paste0("slope = ", format(slope_med,digits=2,scientific=TRUE)),
         interv=paste0(format(slope_med,digits=2,scientific=TRUE)," [",
                       format(slope_q05,digits=2,scientific=TRUE),", ",
                       format(slope_q95,digits=2,scientific=TRUE),"]"))
```

### constant slope
```{r}
fec_biome<-data_fit |> 
  filter(dh_valid) |> 
  filter(!is.na(ISP)) |> 
  filter(!is.na(dh)) |>
  select(- biome) |> 
  group_by(species) |>
  mutate(mid_isp=median(ISP)[[1]]) |>
  ungroup() |>
  filter(!is.na(margin.temp)) |> 
  left_join(species.biome) |> 
  filter(biome!=8) |> 
  mutate(dISP=ISP/mid_isp) |> 
  filter(!is.na(dISP))
  
# output file
out_anova_biome=fec_biome |> 
  mutate(dh_sample=NA,
         med=NA,
         q05=NA,
         q95=NA,
         biome=NA) |> 
  slice(0)
  
for(b in unique(fec_biome$biome)){
  print(b)
  sub_biome=fec_biome |> 
    filter(biome==b) |> 
    filter(!is.na(species)) |> 
    ungroup()
  
  X=model.matrix(~margin.temp*dh, sub_biome)
  model=paste0("anova_",b,".RData")
  
  if(file.exists(file.path(folder,model))){
    load(file.path(folder,model))
  }else{
    stop()
  }
  posteriors_fec<-as.data.frame(fit) |>
    dplyr::select(!matches("beta_")) |>
    dplyr::select(matches("beta"))
  colnames(posteriors_fec)[1:ncol(X)]=colnames(X)
  dh_range=sub_biome |> pull(dh) |> quantile(probs=c(0.05,0.95))
  out_anova_biome=rbind(out_anova_biome,
                        posteriors_fec |> select(`(Intercept)`,dh) |> 
                          crossing(dh_sample=seq(from=dh_range[1],
                                                 to=dh_range[2],
                                                 length.out=500)) |> 
                          mutate(pred=`(Intercept)`+dh_sample*dh) |> 
                          group_by(dh_sample) |> 
                          summarise(med=median(pred),
                                    q05=quantile(pred,probs = 0.05),
                                    q95=quantile(pred,probs = 0.95)) |> 
                          mutate(biome=b) )

}
out_anova_biome=out_anova_biome |>
  mutate(biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Dry",
                         biome==13~"Desert"))  
  ggplot()+
  geom_ribbon(aes(x=dh_sample,ymin=q05,ymax=q95),fill="grey")+
  geom_line(aes(dh_sample,med,color=biome))+
  scale_color_manual(values=c("turquoise3","tomato2","seagreen4","springgreen3"))+
  facet_wrap(~biome,nrow=4,scales="free_y")

fitbiomecontinuous |> 
  mutate(biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Dry",
                         biome==13~"Desert")) |> 
  # filter(margin.temp%in%c("hot")) |> 
  filter(abs(log(dISP)-mean)<7.5) |> 
  group_by(biome) |> 
  filter(dh>quantile(dh,probs=0.05),dh<quantile(dh,probs=0.95)) |> 
  ungroup() |> 
  mutate(dh.cat=as.numeric(as.character(cut(dh,
                    breaks = c(-Inf,-100,-80,-60,-40,-20,0,20,40,60,80,100,Inf),
                    labels =c(-110,-90,-70,-50,-30,-10,10,30,50,70,90,110))))) |> 
  ggplot()+
  geom_ribbon(data=out_anova_biome,aes(x=dh_sample,ymin=q05,ymax=q95),fill="grey")+
  geom_line(data=out_anova_biome,aes(dh_sample,med,color=biome))+
  geom_boxplot(aes(as.numeric(dh.cat),log(dISP)-mean,group=dh.cat,fill=biome),linewidth=0.3,outlier.colour = NA)+
  geom_text(data=slope_biome,aes(label=slope),x=-75,y=-3.3,size=2.5)+
  scale_fill_manual(values=c("turquoise3","tomato2","seagreen4","springgreen3"))+
  scale_color_manual(values=c("turquoise3","tomato2","seagreen4","springgreen3"))+
  common_theme+
  theme(legend.position = "none")+
  ylim(c(-4,4))+
  labs(fill="Biome",
       y="Log ratio of fecundity \n relative to the species mean",
       x="Moisture deficit (mm)")+
  facet_wrap(~biome,nrow = 4) -> a



fec_biome |>  
  group_by(biome,zone,species) |> 
  summarise(cor_dh_mat=cor.test(dh,mat,method="spearman")$estimate[[1]],
            pval_dh_mat=cor.test(dh,mat,method="spearman")$p.value,
            cor_disp_dh=cor.test(dh,dISP,method="spearman")$estimate[[1]],
            pval_disp_dh=cor.test(dh,dISP,method="spearman")$p.value) |>
  mutate(cor_dh_mat=case_when(pval_dh_mat<0.05~cor_dh_mat,
                              TRUE~0),
         cor_disp_dh=case_when(pval_disp_dh<0.05~cor_disp_dh,
                              TRUE~0)) |> 
  mutate(biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Dry",
                         biome==13~"Desert")) |> 
  ggplot(aes(cor_dh_mat,fill=biome))+
  geom_histogram()+
  scale_fill_manual(values=c("turquoise3","tomato2","seagreen4","springgreen3"))+
  geom_vline(xintercept = 0)+
  common_theme+
  theme(legend.position = "none")+
  scale_x_continuous(breaks=c(-0.4,-0.2,0,0.2,0.4,0.6))+
  facet_wrap(~biome,nrow=4)+
  labs(x="Correlation between temperature and moisture deficit",y="Count (species)")->b

cowplot::plot_grid(a,b)->p3
ggsave( p3,
        filename = "figure/main_fig_3_margin.png",
        scale=1.1,
        dpi = 600,
        width = 17,
        height=15,
        units = "cm")

```



## complementary analysis
```{r}
fecundity.fit<-tar_read(fecundity.fit.25,store="target_fit_margin")
tar_load(species.biome,store="target_fit_margin")
data_aridity<-fecundity.fit |> 
  filter(!is.na(ISP)) |> 
  filter(!is.na(dh)) |>
  select(- biome) |> 
  group_by(species) |>
  mutate(mid_isp=median(ISP)[[1]]) |>
  ungroup() |>
  # filter(!is.na(margin.temp)) |>
  left_join(species.biome) |> 
  filter(biome!=8) |> 
  mutate(dISP=ISP/mid_isp) |> 
  filter(!is.na(dISP)) |> 
  filter(dh_valid)

text=data.frame(x=c(-0.4,-0.4,0.6,0.6),
                y=c(-0.6,0.5,-0.6,0.5),
                text=c("Hot margins are humid",
                       "Hot margins are humid",
                       "Hot margins are arid",
                       "Hot margins are arid"),
                type=c("a","a","b","b"),
                text2=c("Fecundity lower when arid",
                        "Fecundity higher when arid",
                        "Fecundity lower when arid",
                        "Fecundity higher when arid"))
data_aridity |> 
  group_by(biome,zone,species) |> 
  summarise(cor_dh_mat=cor.test(dh,mat,method="spearman")$estimate[[1]],
            pval_dh_mat=cor.test(dh,mat,method="spearman")$p.value,
            cor_disp_dh=cor.test(dh,dISP,method="spearman")$estimate[[1]],
            pval_disp_dh=cor.test(dh,dISP,method="spearman")$p.value) |>
  mutate(cor_dh_mat=case_when(pval_dh_mat<0.05~cor_dh_mat,
                              TRUE~0),
         cor_disp_dh=case_when(pval_disp_dh<0.05~cor_disp_dh,
                              TRUE~0)) |> 
  mutate(biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Mediterranean",
                         biome==13~"Desert")) |> 
  ggplot()+
  geom_point(aes(cor_dh_mat,cor_disp_dh,color=as.factor(biome)))+
  geom_hline(yintercept = 0)+geom_vline(xintercept = 0)+
  geom_text(data=text,aes(label=text,x=x,y=y,color=type))+
  geom_text(data=text,aes(label=text2,x=x,y=y,color=type),vjust=2)+
  stat_ellipse(aes(cor_dh_mat,cor_disp_dh,color=as.factor(biome)),
               geom="polygon",level=0.85,alpha=0.2)+
  scale_color_manual(values=c("turquoise3","tomato2","seagreen4","springgreen3","blue","red"))+
  common_theme+
  labs(color="Biome",
       x="Moisture deficit / Temperature correlation",
       y="Moisture deficit / Relative fecundity correlation")+
  xlim(c(-1,1))+ylim(c(-1,1))
  # pivot_longer(cols=c("cor_dh_mat","cor_disp_dh")) |>
  # ggplot(aes(as.factor(biome),value))+
  # geom_boxplot()+geom_hline(yintercept = 0)+geom_vline(xintercept = 0)+
  # facet_grid(~name)
  # 
  
fecundity.fit |> 
  filter(dh_valid) |> 
  
    select(- biome) |> 
      left_join(species.biome) |> 
  filter(biome==12) |> 
  ggplot(aes(dh,mat))+
  geom_point()+
  geom_smooth(aes(color=species),method="lm")

```


# Supplementary material

## Species table

### data
```{r}
fecundity.fit<-tar_read(fecundity.fit.25,store="target_fit_margin")
tar_load(species_selection_large,store="target_nfi")
tar_load(species_selection_narrow,store="target_nfi")
mastif_data<-rbind(tar_read(mastif.eu,store="target_data")$df.tree,
                   tar_read(mastif.am,store="target_data")$df.tree)
phylo.select=tar_read(phylo.select_margin,store="target_nfi") #|>
tar_load(species.biome,store="target_fit_margin")
```

### table

```{r}
mastif_treeyear<-mastif_data |> group_by(species) |> summarise(ntreeyear=n())
nfi_nplots<-fecundity.fit |> group_by(species) |> summarise(nplot=n())

phylo.select |> 
  left_join(species.biome) |> 
  left_join(mastif_treeyear) |> 
  left_join(nfi_nplots) |> 
  mutate(Margin=case_when(cold_valid&hot_valid~"Both",
                          cold_valid&!hot_valid~"Cold",
                          !cold_valid&hot_valid~"Hot")) |> 
  select(species_l,species,taxa,zone,biome,Margin,ntreeyear,nplot) |> 
  mutate(`Biogeographical zone`=case_when(zone %in% c("west","east")~paste0("N.-",
                                                                            toupper(str_sub(zone,1,1)),
                                                                            " Am."),
                                          TRUE~"Europe"),
         biome=case_when(biome==4~"Temp. dec.",
                         biome==5~"Temp. con.",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Dry",
                         biome==13~"Dry"),
         `Large selection`=trunc(as.numeric(species%in%species_selection_large),digits=1),
         `Narrow selection`=trunc(as.numeric(species%in%species_selection_narrow),digits=1)) |> 
  rename(Species=species_l,
         Taxa=taxa,
         Biome=biome,
         `Tree year (MASTIF)`=ntreeyear,
         `NFI plots`=nplot) |> 
  select(Species,Taxa,`Biogeographical zone`,Biome,Margin,`Tree year (MASTIF)`,`NFI plots`,`Large selection`,`Narrow selection`) |> 
  group_by(Species,Taxa,`Biogeographical zone`,Margin,`Tree year (MASTIF)`,`NFI plots`,`Large selection`,`Narrow selection`) %>%
  summarise(Biome = paste(unique(Biome), collapse = ",\\")) |> 
  mutate(Biome=paste0("makecell{",Biome,"}")) |> 
  arrange(Species) |> 
  select(Species,Taxa,`Biogeographical zone`,Biome,Margin,`Tree year (MASTIF)`,`NFI plots`,`Large selection`,`Narrow selection`)-> table
print(xtable::xtable(table),include.rownames=FALSE)
```


## Fig 1


### data
```{r}
fitspecies<-tar_read(fitspecies_25,store="target_fit")
fecundity.fit<-tar_read(fecundity.fit.25,store="target_fit")
fitcontinentdiscrete<-tar_read(fitcontinentdiscrete_25,store="target_fit")
```


### figure
```{r}
data_env<-fecundity.fit |> 
  filter(margin.temp%in%c("cold","hot"))|> 
  group_by(zone,species,margin.temp) |> 
  summarise(med.dh=median(dh),
            med.mat=median(mat)) |> 
  group_by(margin.temp,zone) |> 
  mutate(max.mat=max(med.mat),
         min.mat=min(med.mat)) 
fitcontinentdiscrete |> 
  filter(margin.temp%in%c("cold","hot"))|> 
  mutate(margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold")) |>
  ggplot(aes(x=posterior,y=zone,fill=zone))+
  geom_density_ridges(scale=0.6,color=NA)+
  geom_vline(xintercept = 0)+
  scale_fill_manual(values=c("firebrick4","firebrick1","slateblue"))+
  facet_wrap(~margin.temp,nrow=2)+
  common_theme+
  theme(axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        legend.position = c(0.13,0.13),
        legend.background = element_rect(fill = "white",
                                         size = 0.5),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())+
  labs(x="Relative log-fecundity (species as random effect)",
       title="A. Posterior of continent scale model",
       fill="Zone")->boxp
  
```

```{r}
model_data <- fitspecies |>
  ungroup() |> 
  left_join(data_env,by=c("species","margin.temp")) |> 
  filter(margin.temp%in%c("cold","hot"))|> 
  mutate(margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold")) |> 
  group_by(zone,species,margin.temp,med.mat,max.mat,min.mat) |> 
  summarise(med.ISP=median(posterior),
            q05=quantile(posterior, prob=0.05)[[1]],
            q95=quantile(posterior, prob=0.95)[[1]]) |>
  mutate(signif=!(q05<0&q95>0)) |> ungroup() |> 
  # filter(signif) |> 
  group_by(margin.temp,zone) |> 
  do({
    model = lm(med.ISP ~ med.mat, data = .)
    data.frame(broom::tidy(model), .[1, ])
  }) %>%
  mutate(significant = (p.value < 0.05) & term =="med.mat" ) |> 
  group_by(zone,margin.temp) |>
  filter(sum(significant)>=1) |>
  # filter(zone=="europe") |> 
  dplyr::select(term,estimate,zone,margin.temp,max.mat,min.mat)
model_data=model_data |> 
  pivot_wider(names_from = term,
              values_from = estimate) |> 
  crossing(mat.pred=seq(-10,25,0.1)) |> 
  filter((mat.pred>min.mat)&(mat.pred<max.mat)) |> 
  mutate(pred.isp=`(Intercept)`+mat.pred*med.mat) 

fitspecies |>
  left_join(data_env) |> 
  filter(margin.temp%in%c("cold","hot"))|> # &margin.deficit=="arid" 
  mutate(margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold")) |> 
  group_by(zone,species,margin.temp,med.mat) |> 
  summarise(med.ISP=median(posterior),
            q05=quantile(posterior, prob=0.05)[[1]],
            q95=quantile(posterior, prob=0.95)[[1]]) |> 
  mutate(signif=!(q05<0&q95>0)) |> 
  ungroup() |> 
  ggplot()+
  geom_point(aes(med.mat,med.ISP,color=zone,shape=signif))+
  geom_linerange(aes(x=med.mat,ymin=q05,ymax=q95,color=zone))+
  geom_line(data = model_data,
            aes(mat.pred,pred.isp,color=zone),
            linewidth=1) +
  geom_hline(yintercept = 0,color="gray32")+
  geom_vline(xintercept = 0,color="gray32")+
  common_theme+
  theme(legend.position = "none")+
  scale_color_manual(values=c("firebrick1","slateblue","firebrick4"))+
  scale_shape_manual(values=c(1,19))+
  # scale_y_continuous(breaks = c(-2,-1,-0.5,0.5,1,2))+
  labs(title="B. Posterior at the species scale",
       y="Relative log-fecundity (by species)",
       x="Mean annual temperature of the margin")+
  facet_wrap(~margin.temp,nrow = 2)->plt


cowplot::plot_grid(boxp,plt,ncol=2,rel_widths = c(2,1.5))  -> p
p
# ggsave( p,
#         filename = "figure/supmat_fig_1.png",
#         scale=1.2,
#         dpi = 600,
#         width = 17,
#         height=12,
#         units = "cm")


```
## Fig 2


### Data
```{r}
fitbiomediscrete<-tar_read(fitbiomediscrete_25,store="target_fit_margin")
```


### Figure

```{r}
fitbiomediscrete |> 
  mutate(margin.temp=ifelse(margin.temp=="hot","Hot",
                            ifelse(margin.temp=="cold","Cold","midtemp")),
         margin.temp=factor(margin.temp,levels=c("Cold","midtemp","Hot")),
         biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Dry",
                         biome==13~"Desert")) |> 
  filter(margin.temp!="midtemp") |>
  ggplot(aes(x=posterior,y=biome,fill=biome))+
  geom_density_ridges(scale=0.8,color=NA)+
  geom_vline(xintercept = 0)+
  scale_fill_manual(values=c("turquoise3","tomato2","seagreen4","springgreen2"))+
  facet_wrap(~margin.temp,ncol=2)+
  common_theme+
  theme(axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        legend.position = "right",
        legend.background = element_rect(fill = "white",
                                         size = 0.5),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())+
  labs(x="Posterior of the relative log-fecundity",
       fill="Biome")->p2

ggsave( p2,
        filename = "figure/supmat_fig_2.png",
        scale=1.1,
        dpi = 600,
        width = 15,
        height=5,
        units = "cm")
```

## Fig 3


### data
```{r}
fitbiomecontinuous<-tar_read(fitbiomecontinuous_25,store="target_fit")
```

### Figure

```{r}
fitbiomecontinuous |> 
  mutate(biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Mediterranean",
                         biome==13~"Desert")) |> 
  filter(margin.temp=="cold") |> 
  filter(dh>(-4000)) |> 
  filter(abs(log(dISP)-mean)<7.5) |> 
  mutate(dh.cat=as.numeric(as.character(cut(dh,
                    breaks = c(-Inf,-300,-275,-250,-225,-200,-175,-150,-125,-100,-75,-50,-25,0,25,50,75,100,125,150,175,200,225,250,275,300,Inf),
                    labels = c(-337.5,-287.5,-262.5,-237.5,-212.5,-187.5,-162.5,-137.5,-112.5,-87.5,-62.5,-37.5,-12.5,12.5,37.5,62.5,87.5,112.5,137.5,162.5,187.5,212.5,237.5,262.5,287.5,312.5))))) |> 
  ggplot()+
  # geom_point(aes(dh,log(dISP)-mean,color=margin.temp),size=0.6,alpha=0.05)+
  geom_ribbon(aes(x=dh,ymin=quant05,ymax=quant95,fill=biome),alpha=0.8)+
  geom_line(aes(dh,fit),size=0.2,color="black")+
  geom_boxplot(aes(as.numeric(dh.cat),log(dISP)-mean,group=dh.cat,fill=biome),linewidth=0.3,outlier.colour = NA)+
  # geom_boxplot(aes(dh,y=-12,color=margin.temp),position=position_dodge(width=2),
  #              outlier.colour = NA)+
  scale_fill_manual(values=c("turquoise3","tomato2","seagreen4","springgreen3"))+
  common_theme+
  theme(legend.position = "none")+
  labs(fill="Biome",
       y="Log ratio of fecundity \n relative to the species mean",
       x="Moisture deficit (mm)")+
  facet_wrap(~biome,nrow = 4,scales="free_y")-> p3

ggsave( p3,
        filename = "figure/supmat_fig_3.png",
        scale=1.1,
        dpi = 600,
        width = 8,
        height=15,
        units = "cm")
```

## Fig 4

### Data

```{r}
tar_load(stemData_am,store="target_nfi")
tar_load(stemData_eu,store="target_nfi")
tar_load(species.biome,store="target_fit")
tar_load(phylo.select_margin,store="target_nfi")
```

### Figure

```{r}
thresh=0.33
rbind(stemData_am$plot_shade,stemData_eu$plot_shade) |> 
  filter(species %in% species_selection_narrow) |> 
  group_by(species) |> 
    # compute weighted quantiles of sgdd and wai, and correlation between wai and sgdd
    mutate(margin.temp=case_when(mat<=weighted.quantile(mat,w=BA, prob=thresh)[[1]]~"cold",
                                 mat<weighted.quantile(mat,w=BA, prob=0.5+thresh/2)[[1]]&
                                   mat>weighted.quantile(mat,w=BA, prob=0.5-thresh/2)[[1]]~"midtemp",
                                 mat>=weighted.quantile(mat,w=BA, prob=1-thresh)[[1]]~"hot"),
           margin.temp=factor(margin.temp,levels=c("midtemp","cold","hot")),
           margin.deficit=case_when(dh<weighted.quantile(dh,w=BA, prob=thresh)[[1]]~"humid",
                                    dh<weighted.quantile(dh,w=BA, prob=0.5+thresh/2)[[1]]&
                                      dh>weighted.quantile(dh,w=BA, prob=0.5-thresh/2)[[1]]~"midhum",
                                    dh>weighted.quantile(dh,w=BA, prob=1-thresh)[[1]]~"arid"),
           margin.deficit=factor(margin.deficit,levels=c("midhum","humid","arid"))) |> 
  ungroup() |> 
  left_join(species.biome,by="species") |> 
  filter(biome!=8) |> 
    mutate(biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Mediterranean",
                         biome==13~"Desert")) |> 
  filter(margin.temp%in% c("cold","hot"),margin.deficit %in% c("humid","arid")) |> 
  ggplot(aes(margin.deficit,shade_min))+
  # geom_point(alpha=0.1)+
  # geom_smooth(method="lm")+
  geom_boxplot(outlier.colour = NA)+
  facet_grid(~biome)


data_processed=rbind(stemData_am$plot_shade,stemData_eu$plot_shade) |> 
  filter(species %in% species_selection_narrow) |> 
  group_by(species) |> 
    mutate(margin.temp=case_when(dh<=quantile(dh, probs=thresh,na.rm=TRUE)[[1]]~"humid",
                                 dh<quantile(dh, probs=0.5+thresh/2,na.rm=TRUE)[[1]]&
                                   dh>quantile(dh, probs=0.5-thresh/2,na.rm=TRUE)[[1]]~"midtemp",
                                 dh>=quantile(dh,probs=1-thresh,na.rm=TRUE)[[1]]~"arid")) |> 
  ungroup() |> 
  left_join(species.biome,by="species") |> 
  filter(biome!=8) |> 
    mutate(biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Dry",
                         biome==13~"Desert")) |> 
  # filter(margin.deficit %in% c("humid","arid")) |>
  filter(margin.temp %in% c("humid","arid")) 
coord<- data_processed %>%
  group_by(biome,margin.temp) |> mutate(n_biome=n()) |> 
  group_by(biome,margin.temp,shade_min) |> summarise(prop=n()/n_biome) |> distinct() |> 
  group_by(biome,shade_min) |> summarise(y=max(prop)+0.05)

prop_test_results <- data_processed %>%
  count(biome, shade_min, margin.temp) %>%
  group_by(biome, shade_min) %>%
  summarize(n_hot = sum(n[margin.temp == "humid"], na.rm = TRUE),
            n_cold = sum(n[margin.temp == "arid"], na.rm = TRUE)) %>%
  rowwise() %>%
  mutate(p_value = prop.test(c(n_hot, n_cold), c(sum(n_hot, n_cold), sum(n_hot, n_cold)))$p.value,
         signif=if_else(p_value<0.01,"***",
                        if_else(p_value<0.05,"**",
                                if_else(p_value<0.1,"*","")))) |> 
  left_join(coord) |> 
  filter(shade_min!=0)




ggplot(data=data_processed)+
  geom_bar(aes(shade_min,fill=margin.temp,y=..prop..),stat="count",position="dodge")+
  geom_text(data=prop_test_results,aes(label=signif,x=shade_min,y=y))+
  # stat_compare_means(aes(group = margin.temp,y=1000), method = "t.test", label = "p.signif",)+
  facet_wrap(~biome) +
  labs(x = "Shade Minimum", y = "Proportion", fill = "Temperature region") +
  theme_minimal() +
  scale_fill_manual(values=c("steelblue","orange"))+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        strip.background = element_blank(), 
        strip.text = element_text(face = "bold"),
        legend.position = "top") ->p

p
# ggsave( p,
#         filename = "figure/supmat_fig_4.png",
#         scale=1.2,
#         dpi = 600,
#         width = 12,
#         height=9,
#         units = "cm")

```

