---
title: "Figures"
author: "GEB SUB"
date: "2024-06-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE,message=FALSE)
library(targets)
lapply(c("stringr","tidyr","dplyr","tibble", # data analysis
         "ggplot2","viridis", "ggridges","wesanderson",# plot
         "factoextra", "nlme","modi","rstan","shinystan",# stat & models
         "rworldmap" # geographic data #terre, sf
         ),require,character.only=TRUE)
theme_set(theme_minimal()) # ggplot theme
common_theme <- theme(
  # legend.position = "none",
  strip.background = element_rect(fill = "white",
                                        colour = "gray12"),
  panel.background = element_rect(fill = "white",
                                  colour = "gray12",
                                  size = 0.5, linetype = "solid"),
  plot.title = element_text(size = 12),
  axis.title = element_text(size = 10),
  axis.text = element_text(size = 10),
  strip.text = element_text(size =10),
  plot.margin = unit(c(0, 0.2, 0, 0.2), "cm")  # Example margin; adjust as needed
)

loadRData <- function(fileName){
  #loads an RData file, and returns it
  load(fileName)
  get(ls()[ls() != "fileName"])
}
```


# Results

```{r data, include=FALSE}
# load necessary data #
tar_load(species_selection_large )

## species selection ##
tar_load(sp.select.eu )
tar_load(sp.select.am )
tar_load(species_class )
tar_load(species.biome,store="target_fit")


worldmap <- sf::st_as_sf(getMap(resolution = "high"))

```

## 1

### data
```{r}
fitspecies<-tar_read(fitspecies_25)
fecundity.fit<-tar_read(fecundity.fit.25 )
fitcontinentdiscrete<-tar_read(fitcontinentdiscrete_25 )
```


### figure
```{r}
species_n=fecundity.fit |> 
  filter(margin.temp%in%c("hot","cold")) |> 
  select(zone,margin.temp,species) |> 
  unique() |> 
  group_by(zone,margin.temp) |> 
  summarise(n=paste0("(",n(),")"))

signif<- fitcontinentdiscrete |>
  ungroup() |> 
  group_by(zone,margin.temp) |> 
  summarise(mean=mean(posterior),
            q05=quantile(posterior,prob=0.05),
            q95=quantile(posterior,prob=0.95)) |> 
  mutate(signif=(sign(q05)==sign(q95)))

text=fitcontinentdiscrete |> 
  filter(margin.temp%in%c("cold","hot"))|> 
  group_by(zone,margin.temp) |> summarise(med=median(posterior),ext=min(posterior)-0.1) |> 
  left_join(species_n,by=c("zone","margin.temp")) |>
  left_join(signif) |>
  mutate(star=if_else(signif,"*",""),
         margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold"),
         zone=factor(zone,level=c("west","east","europe")))

data_env<-fecundity.fit |> 
  filter(margin.temp%in%c("cold","hot"))|> 
  group_by(zone,species,margin.temp) |> 
  summarise(med.dh=median(dh),
            med.mat=median(mat)) |> 
  group_by(margin.temp,zone) |> 
  mutate(max.mat=max(med.mat),
         min.mat=min(med.mat)) 
fitcontinentdiscrete |> 
  filter(margin.temp%in%c("cold","hot"))|> 
  mutate(margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold")) |>
  ggplot()+
  geom_density_ridges(aes(x=posterior,y=zone,fill=zone),
                      scale=0.6,color=NA)+
  geom_vline(xintercept = 0)+
  geom_text(data=text,aes(label=star,x=med,y=zone,color=zone),vjust=1.2,size=6)+
  geom_text(data=text,aes(label=n,x=med,y=zone),vjust=-0.5,size=3)+
  scale_fill_manual(values=c("firebrick4","firebrick1","slateblue"))+
  scale_color_manual(values=c("firebrick4","firebrick1","slateblue"),guide="none")+
  facet_wrap(~margin.temp,nrow=2)+
  common_theme+
  theme(axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        legend.position = c(0.13,0.13),
        legend.background = element_rect(fill = "white",
                                         size = 0.5),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())+
  labs(x="Relative log-fecundity (species as random effect)",
       title="A. Posterior of continent scale model",
       fill="Zone") ->boxp
boxp
# ggsave( boxp,
#         filename = "figure/main_fig_1_margin.png",
#         scale=1.2,
#         dpi = 600,
#         width = 17,
#         height=12,
#         units = "cm")

  
```



### results

```{r}
fitcontinentdiscrete |>
  ungroup() |> 
  group_by(margin.temp) |> 
  summarise(mean=mean(posterior),
            q05=quantile(posterior,prob=0.05),
            q95=quantile(posterior,prob=0.95)) |> 
  mutate(signif=(sign(q05)==sign(q95))) |> 
  mutate(ltx=paste0(round(mean,digits = 2)," [",round(q05,digits=2),",",round(q95,digits = 2),"]"))
signif |> 
  mutate(ltx=paste0(round(mean,digits = 2)," [",round(q05,digits=2),",",round(q95,digits = 2),"]"))
```

## 2

### Data
```{r}
fitbiomediscrete<-tar_read(fitbiomediscrete_25 )
fecundity.fit<-tar_read(fecundity.fit.25 )
tar_load(species.biome )
```


### Figure

```{r}
species_n=fecundity.fit |> 
  select(-biome) |> 
  left_join(species.biome) |> 
  filter(margin.temp%in%c("hot","cold")) |> 
  select(biome,margin.temp,species) |> 
  unique() |> 
  group_by(biome,margin.temp) |> 
  summarise(n=paste0("(",n(),")"))

signif<- fitbiomediscrete |>
  ungroup() |> 
  group_by(biome,margin.temp) |> 
  filter(margin.temp %in%  c("cold","hot")) |> 
  summarise(mean=mean(posterior),
            q05=quantile(posterior,prob=0.05),
            q95=quantile(posterior,prob=0.95))|> 
  mutate(signif=(sign(q05)==sign(q95)))

text=fitbiomediscrete |> 
  filter(margin.temp%in%c("cold","hot"))|> 
  group_by(biome,margin.temp) |> summarise(med=median(posterior),ext=min(posterior)-0.1) |> 
  left_join(species_n,by=c("biome","margin.temp")) |>
  left_join(signif) |>
  mutate(star=if_else(signif,"*",""),
         margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold"),
         biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Dry",
                         biome==13~"Desert"))
fitbiomediscrete |> 
  mutate(margin.temp=ifelse(margin.temp=="hot","Hot",
                            ifelse(margin.temp=="cold","Cold","midtemp")),
         margin.temp=factor(margin.temp,levels=c("Cold","midtemp","Hot")),
         biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Dry",
                         biome==13~"Desert")) |> 
  filter(margin.temp!="midtemp") |>
  ggplot()+
  geom_density_ridges(aes(x=posterior,y=biome,fill=biome),
                      scale=1.1,color=NA)+
  geom_text(data=text,aes(label=star,x=med,y=biome,color=biome),vjust=1.2,size=6)+
  geom_text(data=text,aes(label=n,x=med,y=biome),vjust=-0.5,size=3)+
  geom_vline(xintercept = 0)+
  scale_fill_manual(values=c("turquoise3","tomato2","seagreen4","springgreen2"))+
  scale_color_manual(values=c("turquoise3","tomato2","seagreen4","springgreen2"),guide="none")+
  facet_wrap(~margin.temp,ncol=2)+
  common_theme+
  theme(#axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        legend.position = "none",
        # legend.background = element_rect(fill = "white",
        #                                  size = 1),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())+
  labs(x="Posterior of the relative log-fecundity",
       fill="Biome")->p2
p2
# ggsave( p2,
#         filename = "figure/main_fig_2_margin_2.png",
#         scale=1.1,
#         dpi = 600,
#         width = 15,
#         height=8,
#         units = "cm")
```

### Results
```{r}
signif |> 
  mutate(ltx=paste0(round(mean,digits = 2)," [",round(q05,digits=2),",",round(q95,digits = 2),"]"))
# fecundity.fit |> filter(species%in% species_selection_large) |> select(biome,species) |> unique() |> group_by(biome) |> summarise(n=n()) 
```


## 3

### data
```{r}
fitbiomecontinuous<-tar_read(fitbiomecontinuous_25 )
fecundity.fit<-tar_read(fecundity.fit.25 )
species.biome<-tar_read(species.biome )
fitbiomediscrete<-tar_read(fitbiomediscrete_25 )
```

### Figure

```{r}
slope_biome=data.frame(biome=c(4,5,6,12),slope_med=NA,slope_q05=NA,slope_q95=NA)
for (b in 1:dim(slope_biome)[1]){
  fit<-loadRData(paste0("model/biome_continous_25_margin/anova_",slope_biome$biome[b],".RData"))
  post_slope=as.data.frame(fit) |> select(c("beta[1]","beta[4]")) |>
  mutate(slope=`beta[1]`+`beta[4]`) |> summarise(mean=mean(slope),q05=quantile(slope,probs = 0.05),q95=quantile(slope,probs = 0.95))
  slope_biome$slope_med[b]=post_slope$mean
  slope_biome$slope_q05[b]=post_slope$q05
  slope_biome$slope_q95[b]=post_slope$q95
  
}

slope_biome$signif=(sign(slope_biome$slope_q05)==sign(slope_biome$slope_q95))
slope_biome<-slope_biome |> 
  mutate(biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Dry",
                         biome==13~"Desert"),
         slope=paste0("slope = ", format(slope_med,digits=2,scientific=TRUE)),
         interv=paste0(format(slope_med,digits=2,scientific=TRUE)," [",
                       format(slope_q05,digits=2,scientific=TRUE),", ",
                       format(slope_q95,digits=2,scientific=TRUE),"]"))
```

```{r}
fec_biome<-fecundity.fit |> 
  filter(dh_valid) |> 
  filter(!is.na(ISP)) |> 
  filter(!is.na(dh)) |>
  select(- biome) |> 
  group_by(species) |>
  mutate(mid_isp=median(ISP)[[1]]) |>
  ungroup() |>
  filter(!is.na(margin.temp)) |> 
  left_join(species.biome) |> 
  filter(biome!=8) |> 
  mutate(dISP=ISP/mid_isp) |> 
  filter(!is.na(dISP))
  
# output file
out_anova_biome=fec_biome |> 
  mutate(dh_sample=NA,
         med=NA,
         q05=NA,
         q95=NA,
         biome=NA) |> 
  slice(0)
folder="model/biome_continous_25_margin"  
for(b in unique(fec_biome$biome)){
  print(b)
  sub_biome=fec_biome |> 
    filter(biome==b) |> 
    filter(!is.na(species)) |> 
    ungroup()
  
  X=model.matrix(~margin.temp*dh, sub_biome)
  model=paste0("anova_",b,".RData")
  
  if(file.exists(file.path(folder,model))){
    load(file.path(folder,model))
  }else{
    stop()
  }
  posteriors_fec<-as.data.frame(fit) |>
    dplyr::select(!matches("beta_")) |>
    dplyr::select(matches("beta"))
  colnames(posteriors_fec)[1:ncol(X)]=colnames(X)
  dh_range=sub_biome |> pull(dh) |> quantile(probs=c(0.05,0.95))
  out_anova_biome=rbind(out_anova_biome,
                        posteriors_fec |> select(`(Intercept)`,dh) |> 
                          crossing(dh_sample=seq(from=dh_range[1],
                                                 to=dh_range[2],
                                                 length.out=500)) |> 
                          mutate(pred=`(Intercept)`+dh_sample*dh) |> 
                          group_by(dh_sample) |> 
                          summarise(med=median(pred),
                                    q05=quantile(pred,probs = 0.05),
                                    q95=quantile(pred,probs = 0.95)) |> 
                          mutate(biome=b) )

}
out_anova_biome<-out_anova_biome|> 
  mutate(biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Dry",
                         biome==13~"Desert"))
fitbiomecontinuous |> 
  mutate(biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Dry",
                         biome==13~"Desert")) |> 
  # filter(margin.temp%in%c("hot")) |> 
  filter(abs(log(dISP)-mean)<7.5) |> 
  group_by(biome) |> 
  filter(dh>quantile(dh,probs=0.05),dh<quantile(dh,probs=0.95)) |> 
  ungroup() |> 
  mutate(dh.cat=as.numeric(as.character(cut(dh,
                    breaks = c(-Inf,-100,-80,-60,-40,-20,0,20,40,60,80,100,Inf),
                    labels =c(-110,-90,-70,-50,-30,-10,10,30,50,70,90,110))))) |> 
  ggplot()+
  geom_ribbon(data=out_anova_biome,aes(x=dh_sample,ymin=q05,ymax=q95),fill="grey")+
  geom_line(data=out_anova_biome,aes(dh_sample,med,color=biome))+
  geom_boxplot(aes(as.numeric(dh.cat),log(dISP)-mean,group=dh.cat,fill=biome),linewidth=0.3,outlier.colour = NA)+
  geom_text(data=slope_biome,aes(label=slope),x=-75,y=-3.3,size=2.5)+
  scale_fill_manual(values=c("turquoise3","tomato2","seagreen4","springgreen3"))+
  scale_color_manual(values=c("turquoise3","tomato2","seagreen4","springgreen3"))+
  common_theme+
  theme(legend.position = "none")+
  ylim(c(-4,4))+
  labs(fill="Biome",
       y="Log ratio of fecundity \n relative to the species mean",
       x="Moisture deficit (mm)")+
  facet_wrap(~biome,nrow = 4) -> a



fec_biome |>  
  group_by(biome,zone,species) |> 
  summarise(cor_dh_mat=cor.test(dh,mat,method="spearman")$estimate[[1]],
            pval_dh_mat=cor.test(dh,mat,method="spearman")$p.value,
            cor_disp_dh=cor.test(dh,dISP,method="spearman")$estimate[[1]],
            pval_disp_dh=cor.test(dh,dISP,method="spearman")$p.value) |>
  mutate(cor_dh_mat=case_when(pval_dh_mat<0.05~cor_dh_mat,
                              TRUE~0),
         cor_disp_dh=case_when(pval_disp_dh<0.05~cor_disp_dh,
                              TRUE~0)) |> 
  mutate(biome=case_when(biome==4~"Temperate deciduous",
                         biome==5~"Temperate coniferous",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Dry",
                         biome==13~"Desert")) |> 
  ggplot(aes(cor_dh_mat,fill=biome))+
  geom_histogram()+
  scale_fill_manual(values=c("turquoise3","tomato2","seagreen4","springgreen3"))+
  geom_vline(xintercept = 0)+
  common_theme+
  theme(legend.position = "none")+
  scale_x_continuous(breaks=c(-0.4,-0.2,0,0.2,0.4,0.6))+
  facet_wrap(~biome,nrow=4)+
  labs(x="Correlation between temperature and moisture deficit",y="Count (species)")->b

cowplot::plot_grid(a,b)->p3
# ggsave( p3,
#         filename = "figure/main_fig_3_margin.png",
#         scale=1.1,
#         dpi = 600,
#         width = 17,
#         height=15,
#         units = "cm")

```

# Supplementary material

## Species table

### data
```{r}
fecundity.fit<-tar_read(fecundity.fit.25 )
tar_load(species_selection_quant )
tar_load(species_selection_rank )
mastif_data<-rbind(tar_read(mastif.eu)$df.tree,
                   tar_read(mastif.am)$df.tree)
phylo.select=tar_read(phylo.select ) #|>
tar_load(species.biome )
```

### table

```{r}
mastif_treeyear<-mastif_data |> group_by(species) |> summarise(ntreeyear=n())
nfi_nplots<-fecundity.fit |> group_by(species) |> summarise(nplot=n())

phylo.select |> 
  left_join(species.biome) |> 
  left_join(mastif_treeyear) |> 
  left_join(nfi_nplots) |> 
  mutate(Margin=case_when(cold_valid&hot_valid~"Both",
                          cold_valid&!hot_valid~"Cold",
                          !cold_valid&hot_valid~"Hot")) |> 
  select(species_l,species,taxa,zone,biome,Margin,ntreeyear,nplot) |> 
  mutate(`Biogeographical zone`=case_when(zone %in% c("west","east")~paste0("N.-",
                                                                            toupper(str_sub(zone,1,1)),
                                                                            " Am."),
                                          TRUE~"Europe"),
         biome=case_when(biome==4~"Temp. dec.",
                         biome==5~"Temp. con.",
                         biome==6~"Boreal",
                         biome==8~"Temperate Grasslands",
                         biome==12~"Dry",
                         biome==13~"Dry"),
         `Large selection`=trunc(as.numeric(species%in%species_selection_quant),digits=1),
         `Narrow selection`=trunc(as.numeric(species%in%species_selection_rank),digits=1)) |> 
  rename(Species=species_l,
         Taxa=taxa,
         Biome=biome,
         `Tree year (MASTIF)`=ntreeyear,
         `NFI plots`=nplot) |> 
  select(Species,Taxa,`Biogeographical zone`,Biome,Margin,`Tree year (MASTIF)`,`NFI plots`,`Large selection`,`Narrow selection`) |> 
  group_by(Species,Taxa,`Biogeographical zone`,Margin,`Tree year (MASTIF)`,`NFI plots`,`Large selection`,`Narrow selection`) %>%
  summarise(Biome = paste(unique(Biome), collapse = ",\\")) |> 
  mutate(Biome=paste0("makecell{",Biome,"}")) |> 
  arrange(Species) |> 
  select(Species,Taxa,`Biogeographical zone`,Biome,Margin,`Tree year (MASTIF)`,`NFI plots`,`Large selection`,`Narrow selection`)-> table
print(xtable::xtable(table),include.rownames=FALSE)
```

## Fig 1 - regressions 


### data
```{r}
fitspecies<-tar_read(fitspecies_25 )
fecundity.fit<-tar_read(fecundity.fit.25 )
fitcontinentdiscrete<-tar_read(fitcontinentdiscrete_25 )
```


### Figure
```{r}
data_env<-fecundity.fit |> 
  filter(margin.temp%in%c("cold","hot"))|> 
  group_by(zone,species,margin.temp) |> 
  summarise(med.dh=median(dh),
            med.mat=median(mat)) |> 
  group_by(margin.temp,zone) |> 
  mutate(max.mat=max(med.mat),
         min.mat=min(med.mat)) 

# by biogeo zone
model_data <-fitspecies |>
  ungroup() |> 
  left_join(data_env,by=c("species","margin.temp")) |> 
  filter(margin.temp%in%c("cold","hot"))|> 
  mutate(margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold")) |> 
  group_by(zone,species,margin.temp,med.mat,max.mat,min.mat) |> 
  summarise(med.ISP=median(posterior),
            q05=quantile(posterior, prob=0.05)[[1]],
            q95=quantile(posterior, prob=0.95)[[1]]) |>
  mutate(signif=!(q05<0&q95>0)) |> ungroup() |> 
  # filter(signif) |> 
  group_by(margin.temp,zone) |> 
  do({
    model = lm(med.ISP ~ med.mat, data = .)
    anova_result <- anova(model)
    p_value <- anova_result$`Pr(>F)`[1]
    data.frame(broom::tidy(model), p_value = p_value, .[1, ])
  }) %>% 
  filter(p_value<0.01) |>
  # filter(zone=="europe") |> 
  dplyr::select(term,estimate,zone,margin.temp,max.mat,min.mat)
model_data=model_data |> 
  pivot_wider(names_from = term,
              values_from = estimate) |> 
  crossing(mat.pred=seq(-10,25,0.1)) |> 
  filter((mat.pred>min.mat)&(mat.pred<max.mat)) |> 
  mutate(pred.isp=`(Intercept)`+mat.pred*med.mat) 

fitspecies |>
  left_join(data_env) |> 
  filter(margin.temp%in%c("cold","hot"))|> # &margin.deficit=="arid" 
  mutate(margin.temp=case_when(margin.temp=="hot"~"Hot",
                               margin.temp=="cold"~"Cold")) |> 
  group_by(zone,species,margin.temp,med.mat) |> 
  summarise(med.ISP=median(posterior),
            q05=quantile(posterior, prob=0.05)[[1]],
            q95=quantile(posterior, prob=0.95)[[1]]) |> 
  mutate(signif=!(q05<0&q95>0)) |> 
  ungroup() |> 
  ggplot()+
  geom_point(aes(med.mat,med.ISP,color=zone,shape=signif),size=0.5)+
  geom_linerange(aes(x=med.mat,ymin=q05,ymax=q95,color=zone),size=0.4)+
  geom_line(data = model_data,
            aes(mat.pred,pred.isp,color=zone),
            linewidth=0.4) +
  geom_hline(yintercept = 0,color="gray32")+
  geom_vline(xintercept = 0,color="gray32")+
  common_theme+
  theme(legend.position = "right",
        legend.margin = margin(c(1,25,1,1)))+
  scale_color_manual(values=c("firebrick1","slateblue","firebrick4"))+
  scale_shape_manual(values=c(1,19),guide="none")+
  # scale_y_continuous(breaks = c(-2,-1,-0.5,0.5,1,2))+
  labs(title="By biogeographical zone",
       y="Relative log-fecundity \n(by species)",
       x="Mean annual temperature of the margin",
       color="")+
  facet_wrap(~margin.temp,ncol = 2)-> figzone

# ggsave("supmat_fig_1_regressions.png",plot=figzone+labs(title=""),
#        width=15,height = 6,units="cm",dpi=600)
```
